name: Auto Merge Gate

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  enable-automerge:
    if: |
      (github.event_name != 'pull_request_review') ||
      (github.event.review.state == 'APPROVED')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for labeled PRs
        if: |
          contains(github.event.pull_request.labels.*.name, 'automerge') &&
          !contains(github.event.pull_request.labels.*.name, 'do-not-merge')
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
